# Generated by Django 5.2.17 on 2026-10-01 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='identificador')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('tipo', models.CharField(choices=[('dashboard', 'Dashboard'), ('sitio', 'Sitio')], default='dashboard', max_length=20, verbose_name='tipo')),
                ('organismo', models.CharField(blank=True, max_length=200, verbose_name='organismo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='versión')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado')], default='borrador', max_length=20, verbose_name='estado')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarcar para ocultarlo a todos sin borrarlo.', verbose_name='publicado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('grupos', models.ManyToManyField(blank=True, help_text='Solo los usuarios de estos grupos ven el paquete. El superusuario ve todo.', related_name='paquetes', to='auth.group', verbose_name='grupos con acceso')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'ordering': ['-fecha', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='VersionPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='versión')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado')], default='borrador', max_length=20, verbose_name='estado')),
                ('meta', models.JSONField(default=dict, verbose_name='meta.json')),
                ('carpeta', models.CharField(help_text='Relativa a PAQUETES_ROOT.', max_length=300, verbose_name='carpeta')),
                ('archivo_nombre', models.CharField(blank=True, max_length=255, verbose_name='zip subido')),
                ('tamano_bytes', models.BigIntegerField(default=0, verbose_name='tamaño descomprimido')),
                ('cantidad_archivos', models.PositiveIntegerField(default=0, verbose_name='archivos')),
                ('subido', models.DateTimeField(auto_now_add=True, verbose_name='subido')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='portal.paquete')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'versión de paquete',
                'verbose_name_plural': 'versiones de paquetes',
                'ordering': ['-subido'],
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='version_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.versionpaquete', verbose_name='versión publicada'),
        ),
    ]
