# Generated by Django 5.2.17 on 2026-10-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='novedades',
            field=models.TextField(blank=True, verbose_name='novedades de esta versión'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='resumen',
            field=models.TextField(blank=True, help_text='Párrafo formal para la carta y la confirmación.', verbose_name='resumen'),
        ),
        migrations.CreateModel(
            name='AccesoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash del token')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='carta generada')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último ingreso con el enlace')),
                ('paquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.paquete', verbose_name='paquete de la carta')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enlace personal',
                'verbose_name_plural': 'enlaces personales',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('correo', 'Correo')], max_length=10, verbose_name='medio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=10, verbose_name='estado')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('enviado', models.DateTimeField(blank=True, null=True, verbose_name='enviado')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='portal.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='portal.versionpaquete')),
            ],
            options={
                'verbose_name': 'aviso de actualización',
                'verbose_name_plural': 'avisos de actualización',
                'ordering': ['estado', '-creado'],
            },
        ),
    ]
