# Generated by Django 5.2.17 on 2026-09-28 23:51

import cuentas.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=150, verbose_name='nombre')),
                ('organismo', models.CharField(blank=True, help_text='Solo informativo. Los permisos se dan con los grupos.', max_length=150, verbose_name='organismo')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite entrar al panel de administración.', verbose_name='acceso al admin')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcar en lugar de borrar para quitar el acceso.', verbose_name='activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='alta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['email'],
            },
            managers=[
                ('objects', cuentas.models.UsuarioManager()),
            ],
        ),
    ]
