# Generated by Django 5.2.17 on 2026-10-01 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, help_text='Opcional. Para avisos por WhatsApp. Formato: +5493854123456. Dato personal: no se muestra fuera del admin.', max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Formato internacional, sin espacios ni guiones: + código de país, 9 y número. Ej.: +5493854123456')], verbose_name='celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tratamiento',
            field=models.CharField(blank=True, help_text='Opcional. Sr., Sra., Lic., Dr., Cra., etc.', max_length=20, verbose_name='tratamiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre y apellido completos, ej. María Pérez.', max_length=150, verbose_name='nombre'),
        ),
    ]
