# Generated by Django 5.2.17 on 2026-09-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('organismo', models.CharField(max_length=200, verbose_name='organismo o cliente')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('resumen', models.TextField(blank=True, help_text='Una o dos oraciones, opcional.', max_length=400, verbose_name='resumen')),
                ('imagen', models.ImageField(blank=True, upload_to='proyectos/', verbose_name='imagen')),
                ('texto_alternativo', models.CharField(blank=True, help_text='Qué muestra la imagen, para lectores de pantalla y buscadores.', max_length=200, verbose_name='texto alternativo de la imagen')),
                ('publicado', models.BooleanField(default=False, verbose_name='publicado')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Menor número = aparece primero.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['orden', '-anio', 'titulo'],
            },
        ),
    ]
