# Generated by Django 5.2.17 on 2026-09-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('recibido', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
                ('leido', models.BooleanField(default=False, verbose_name='leído')),
                ('aviso_enviado', models.BooleanField(default=False, verbose_name='aviso por correo enviado')),
                ('aviso_error', models.TextField(blank=True, verbose_name='error del aviso')),
            ],
            options={
                'verbose_name': 'mensaje de contacto',
                'verbose_name_plural': 'mensajes de contacto',
                'ordering': ['-recibido'],
            },
        ),
    ]
